# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bafc40b3f317cd5ba835d729bdd2fa1105a564d1b735bfd6c0c23780150b5ac2920e74fcfa6bf8932e11fb82335d9bd52539211ddad685c58449cea2980a6ada
  public_key: 0f0f7da6a2558fbfd5b9ecaa575b8ffb
  private_key: ba23f67cdb0be9ecc069e9cc43ff713c9fb93461

test:
  secret_key_base: 1b6ae1096d4e27262871ee99285bc477374414492b060d72238caffe8b788842279df0064dcc3b48b673fa43865db664207c3dc3429fdfbc2d072d205c86ec39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
